@startuml

class shape_adm3 {
    id
    geometry
    name
}

class shape_adm2 {
    id
    geometry
    name
}

class shape_adm1 {
    id
    geometry
    name
}

class shape_adm0 {
    id
    geometry
    name
}

@enduml