@startuml

!include dimensions.iuml

class firms {
    geometry
    adm0
    adm1
    adm2
    adm3
    brightness
    frp
    daynight
    scan
    track
    confidence
    type
    instrument
    datetime
}

firms .up. shape_adm0
firms .right. shape_adm1
firms .down. shape_adm2
firms .left. shape_adm3

@enduml